#!/usr/bin/env python3
#
# GlideKVM -- mouse and keyboard sharing utility
# Copyright (C) GlideKVM contributors
#
# This package is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# found in the file LICENSE that should have accompanied this file.
#
# Usage: python3 res/brand/make_small_icon.py res/brand/glidekvm-icon.svg (needs shapely)

# Builds the small GlideKVM icon (64x64): monitor, mouse and a small cursor,
# with a gap wherever one shape sits on another.
import sys
from shapely.geometry import Polygon, LineString, box
from shapely.affinity import scale, translate, rotate
from shapely.ops import unary_union

GAP = 2.4

def rrect(x0, y0, x1, y1, r):
    return box(x0 + r, y0 + r, x1 - r, y1 - r).buffer(r, quad_segs=10)

# monitor: frame with a deeper chin, screen opening, stand
monitor_outer = rrect(3, 7, 49, 41, 5)
screen = rrect(7.5, 11.5, 44.5, 34, 1.5)
frame = monitor_outer.difference(screen)
neck = Polygon([(23, 41), (29, 41), (30.5, 46.5), (21.5, 46.5)])
base = rrect(15, 45.5, 37, 50.5, 2.5)
monitor = unary_union([frame, neck, base])

# mouse: an outlined stadium overlapping the monitor's lower right
mouse_outer = LineString([(51, 37), (51, 47)]).buffer(9.5, quad_segs=12)
mouse_inner = LineString([(51, 37), (51, 47)]).buffer(5.5, quad_segs=12)
mouse_ring = mouse_outer.difference(mouse_inner)
wheel = LineString([(51, 32.5), (51, 36.5)]).buffer(1.6, quad_segs=8)
mouse = unary_union([mouse_ring, wheel])

# cursor: the logo's arrow, small, on the screen
arrow = Polygon([(0, 0), (0, 104), (27, 79), (46, 120), (63, 112), (44, 72), (80, 72)])
arrow = scale(arrow, 0.15, 0.15, origin=(0, 0))
arrow = rotate(arrow, -10, origin=(0, 0))
arrow = translate(arrow, 29, 21)

# gaps: the mouse cuts the monitor; the cursor cuts the monitor
monitor = monitor.difference(mouse_outer.buffer(GAP))
monitor = monitor.difference(arrow.buffer(GAP, join_style=1))
shape = unary_union([monitor, mouse, arrow])

def path(geom):
    out = ''
    for poly in getattr(geom, 'geoms', [geom]):
        for ring in [poly.exterior, *poly.interiors]:
            out += 'M' + 'L'.join('%.2f %.2f' % c for c in list(ring.coords)[:-1]) + 'Z'
    return out

svg = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <title>GlideKVM</title>
  <defs>
    <linearGradient id="g" gradientUnits="userSpaceOnUse" x1="2" y1="4" x2="62" y2="60">
      <stop offset="0" stop-color="#3EEBE0"/>
      <stop offset="0.5" stop-color="#3B9BFF"/>
      <stop offset="1" stop-color="#8E5CF7"/>
    </linearGradient>
  </defs>
  <!-- generated by res/brand/make_small_icon.py -->
  <path fill="url(#g)" fill-rule="evenodd" d="%s"/>
</svg>
''' % path(shape)
open(sys.argv[1], 'w').write(svg)
