
set(GLIDEKVM_VERSION_MAJOR 1)
set(GLIDEKVM_VERSION_MINOR 0)
set(GLIDEKVM_VERSION_PATCH 0)
if((NOT DEFINED GLIDEKVM_VERSION_DESC) OR (GLIDEKVM_VERSION_DESC STREQUAL git))
    find_program (GIT_BINARY git)
    if (GIT_BINARY STREQUAL "GIT_BINARY-NOTFOUND")
        set(GLIDEKVM_VERSION_DESC unknown)
    else()
        execute_process (
            COMMAND git log --pretty=format:'git-%cs-%h' -1
            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
            OUTPUT_VARIABLE GLIDEKVM_VERSION_DESC
            OUTPUT_STRIP_TRAILING_WHITESPACE
        )
    endif()
endif()

string(TIMESTAMP GLIDEKVM_BUILD_DATE "%Y%m%d" UTC)
string(TIMESTAMP GLIDEKVM_BUILD_TIME "%H%M" UTC)
string(TIMESTAMP GLIDEKVM_BUILD_DATE_ISO "%Y-%m-%d" UTC)

set(GLIDEKVM_VERSION "${GLIDEKVM_VERSION_MAJOR}.${GLIDEKVM_VERSION_MINOR}.${GLIDEKVM_VERSION_PATCH}-${GLIDEKVM_VERSION_DESC}")
message(STATUS "Full GlideKVM version string is '" ${GLIDEKVM_VERSION} "'")

add_definitions(-DGLIDEKVM_VERSION="${GLIDEKVM_VERSION}")
add_definitions(-DGLIDEKVM_VERSION_STRING="${GLIDEKVM_VERSION_STRING}")
add_definitions(-DGLIDEKVM_VERSION_MAJOR=${GLIDEKVM_VERSION_MAJOR})
add_definitions(-DGLIDEKVM_VERSION_MINOR=${GLIDEKVM_VERSION_MINOR})
add_definitions(-DGLIDEKVM_VERSION_PATCH=${GLIDEKVM_VERSION_PATCH})
add_definitions(-DGLIDEKVM_REVISION="${GLIDEKVM_REVISION}")
add_definitions(-DGLIDEKVM_BUILD_DATE="${GLIDEKVM_BUILD_DATE}")

