
set(BLUEBRIDGE_VERSION_MAJOR 3)
set(BLUEBRIDGE_VERSION_MINOR 0)
set(BLUEBRIDGE_VERSION_PATCH 3)
if((NOT DEFINED BLUEBRIDGE_VERSION_DESC) OR (BLUEBRIDGE_VERSION_DESC STREQUAL git))
    find_program (GIT_BINARY git)
    if (GIT_BINARY STREQUAL "GIT_BINARY-NOTFOUND")
        set(BLUEBRIDGE_VERSION_DESC unknown)
    else()
        execute_process (
            COMMAND git log --pretty=format:'git-%cs-%h' -1
            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
            OUTPUT_VARIABLE BLUEBRIDGE_VERSION_DESC
            OUTPUT_STRIP_TRAILING_WHITESPACE
        )
    endif()
endif()

string(TIMESTAMP BLUEBRIDGE_BUILD_DATE "%Y%m%d" UTC)
string(TIMESTAMP BLUEBRIDGE_BUILD_TIME "%H%M" UTC)
string(TIMESTAMP BLUEBRIDGE_BUILD_DATE_ISO "%Y-%m-%d" UTC)

set(BLUEBRIDGE_VERSION "${BLUEBRIDGE_VERSION_MAJOR}.${BLUEBRIDGE_VERSION_MINOR}.${BLUEBRIDGE_VERSION_PATCH}-${BLUEBRIDGE_VERSION_DESC}")
message(STATUS "Full BlueBridge version string is '" ${BLUEBRIDGE_VERSION} "'")

add_definitions(-DBLUEBRIDGE_VERSION="${BLUEBRIDGE_VERSION}")
add_definitions(-DBLUEBRIDGE_VERSION_STRING="${BLUEBRIDGE_VERSION_STRING}")
add_definitions(-DBLUEBRIDGE_VERSION_MAJOR=${BLUEBRIDGE_VERSION_MAJOR})
add_definitions(-DBLUEBRIDGE_VERSION_MINOR=${BLUEBRIDGE_VERSION_MINOR})
add_definitions(-DBLUEBRIDGE_VERSION_PATCH=${BLUEBRIDGE_VERSION_PATCH})
add_definitions(-DBLUEBRIDGE_REVISION="${BLUEBRIDGE_REVISION}")
add_definitions(-DBLUEBRIDGE_BUILD_DATE="${BLUEBRIDGE_BUILD_DATE}")

